### PR TITLE
terminado 0.16.0, add cli version check

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Notes:
- only use hatchling
- adds version check

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
Hm... all the arch-specific issues makes me think #39 might be our jam...

**Comment by blink1073** [comment]
Yeah that sounds right

**Comment by blink1073** [comment]
@conda-forge-admin, please rerender

**Comment by blink1073** [comment]
@conda-forge-admin, please rerender

**Comment by blink1073** [comment]
@conda-forge-admin, please rerender

**Comment by blink1073** [comment]
I'm ready to merge if you are!

**Comment by bollwyvl** [comment]
Afk, go for it!

**Comment by bollwyvl** [comment]
Thanks!

**Comment by bollwyvl** [comment]
windows being windows, it did flake on the `main` build... rekicked, will monitor... but 10% of the builds is a lot easier to manage

**Comment by bollwyvl** [comment]
Windows build finally up!

**Comment by blink1073** [comment]
🎉

**Pull request merged**
